# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 792b0f22eb21ead0db4a25bf1d686520a63b1c965f57aa44e1a224780f4f47381eeffcdbe314a06d7c98ab66f48b4c4ad2ab6c44ed5993c676dbc22028dc6cda

test:
  secret_key_base: 509a74ae4891a749e51dec04c0133f7e8844af513b2b384ebedf49c933699b9b1bf6258e643cf0aae15e68bf3347547c4f3f7a3fc36b6ef83ca0b88fa07ff27d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
